name: Release
# This workflow is triggered manually
on:
  workflow_dispatch:
    inputs:
      version_bump_type:
        description: 'Version Bump Type (major, minor, patch)'
        required: true
        default: 'patch'
      version_metadata_path:
        description: 'Path to file containing Version string'
        required: true
        default: 'pkg/version/version.go'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    container: ghcr.io/packagrio/packagr:latest-golang
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Bump version
        id: bump_version
        uses: packagrio/action-bumpr-go@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version_bump_type: ${{ github.event.inputs.version_bump_type }}
          version_metadata_path: ${{ github.event.inputs.version_metadata_path }}
      - name: Test
        run: |
          make clean test
      - name: Commit Changes
        id: commit
        uses: packagrio/action-releasr-go@master
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
      - name: Upload workspace
        uses: actions/upload-artifact@v3
        with:
          name: workspace
          path: ${{ github.workspace }}/**/*
          retention-days: 1
  build:
    name: Build ${{ matrix.cfg.goos }}/${{ matrix.cfg.goarch }}
    needs: release
    runs-on: ${{ matrix.cfg.on }}
    env:
      GOOS: ${{ matrix.cfg.goos }}
      GOARCH: ${{ matrix.cfg.goarch }}
      GOARM: ${{ matrix.cfg.goarm }}
    strategy:
      matrix:
        cfg:
          - { on: ubuntu-latest,  goos: linux,      goarch: amd64 }
          - { on: ubuntu-latest,  goos: linux,      goarch: arm,    goarm: 5 }
          - { on: ubuntu-latest,  goos: linux,      goarch: arm,    goarm: 6 }
          - { on: ubuntu-latest,  goos: linux,      goarch: arm,    goarm: 7 }
          - { on: ubuntu-latest,  goos: linux,      goarch: arm64 }
          - { on: macos-latest,   goos: darwin,     goarch: amd64 }
          - { on: macos-latest,   goos: darwin,     goarch: arm64 }
          - { on: macos-latest,   goos: freebsd,    goarch: amd64 }
          - { on: macos-latest,   goos: freebsd,    goarch: arm64 }
          - { on: windows-latest, goos: windows,    goarch: amd64 }
          - { on: windows-latest, goos: windows,    goarch: arm64 }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18.3' # The Go version to download (if necessary) and use.
      - name: Build
        run: |
          make clean build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hatchet
          path: hatchet-${{ matrix.cfg.goos }}-${{ matrix.cfg.goarch }}*
          retention-days: 1
  release-binaries:
    name: Release Binaries
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download workspace
        uses: actions/download-artifact@v3
        with:
          name: workspace
      - name: Download binaries
        uses: actions/download-artifact@v3
        with:
          name: hatchet
      - name: List
        shell: bash
        run: |
          ls -alt
      - name: Publish Release
        id: publish
        uses: packagrio/action-publishr-go@master
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        with:
          upload_assets: |
            hatchet-linux-amd64
            hatchet-linux-arm-5
            hatchet-linux-arm-6
            hatchet-linux-arm-7
            hatchet-linux-arm64
            hatchet-darwin-amd64
            hatchet-darwin-arm64
            hatchet-freebsd-amd64
            hatchet-freebsd-arm64
            hatchet-windows-amd64.exe
            hatchet-windows-arm64.exe
